spring:
  profiles:
    active: local-dev

---
spring.profiles: local-dev
spring:
  profiles:
    include: local-postgresql-credentials
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/online-store
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  profiles: local-postgresql-credentials
  datasource:
    username: postgres
    password: 1234567890

---
